Preparing the dataframe for training

In [27]:
import numpy as np
import pandas as pd
x_train = np.array([
    [0,0],
    [1,1],
    [1,0],
    [0,1]
])
y_train = np.array([
    [0],
    [1],
    [0],
    [0]
])
r,c = x_train.shape
# y_train.shape
#Combining the features and respective outputs
data = np.hstack((x_train,y_train))
#Converting it into dataframe 
df = pd.DataFrame(data, columns=["x1","x2","y"])
print(df)
print(x_train[0][1])

   x1  x2  y
0   0   0  0
1   1   1  1
2   1   0  0
3   0   1  0
0


Preparing the weight matrix for Wxh (between input and hidden layer) and Who (between hidden and output layer)

In [28]:
#defining the number of neurons in each layer to make it more systematic. The ANN consists of 3 layers, in input layer : 2, hidden layer : 3, output layer : 1 neurons respectively
x_n = 2
h_n = 3
o_n = 1

#defining the weight matrix 
np.random.seed(42)
Wxh = np.random.randn(x_n,h_n)   #randn (n) for normalization  shape (2,3)
Who = np.random.randn(h_n,o_n)   #randn (n) for normalization  shape (3,1)
print(Wxh)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]]


Equations for forward propagation 

We have 4 forward propagation equations. In the hidden layer, we have sigmoid activation function, then in the output layer we have sigmoid activation func as well.

In [29]:
def sigmoid(x):
    result = 1/(1 + np.exp(-x))
    return result 

In [30]:
ua_h = x_train @ Wxh         #shape = (4,3)

a_h = sigmoid(ua_h)          #shape = (4,3)

ua_o = a_h @ Who             #shape = (4,1)

output = sigmoid(ua_o)       #shape = (4,1)
print(output)

[[0.71881406]
 [0.80607425]
 [0.73707158]
 [0.80660888]]


Cost error used here : Mean Squared Error

In [31]:
sq_term = np.square(output - y_train)
mse = np.mean(sq_term)


Backward Propagation

In [32]:
def transpose(x):
      r,c = x.shape
      L = []
      
      for i in range(c):
            l = []
            for j in range(r):
                  l.append(x[j][i])
            L.append(l)
            del(l)
      result = np.array(L)
      return result
      
print(transpose(x_train))

[[0 1 1 0]
 [0 1 0 1]]


In [33]:
#finding gradients wrt Wxh and Who, considering j is the mean squared error
#to find out first, wrt Wxh, we need to find dj/do, do/dua_o, du_o/da_h, da_h/dua_h, dua_h/dWxh
first_term = (y_train - output) @ sigmoid(ua_o)(1 - sigmoid(ua_o))      #(4,1)
# second_term = first_term @ transpose(Who)                              #(4,3)
# third_term = second_term @ sigmoid(ua_h)(1 - sigmoid(ua_h))            #(4,3)
# djdWxh = transpose(x_train) @ third_term                               #(2,3)

# djdWho = transpose(a_h) @ first_term                                   #(3,1)

TypeError: 'numpy.ndarray' object is not callable

checking if my function is same as sigmoid derivative or not

In [ ]:
def sigmoid_derivatives(x):
    num = np.exp(-x)
    term = 1 + np.exp(-x)
    denom = term ** 2
    return num/denom
result = sigmoid_derivatives(x_train)
print(result)

[[0.25       0.25      ]
 [0.19661193 0.19661193]
 [0.19661193 0.25      ]
 [0.25       0.19661193]]


In [35]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

print(sigmoid_derivative(x_train))


[[0.25       0.25      ]
 [0.19661193 0.19661193]
 [0.19661193 0.25      ]
 [0.25       0.19661193]]
